futurice/symptomradar

- frontend/embed/v1/public/index.html
- Add `rel="noopener noreferrer"` in links to improve security
- Remove aria attribute that is not needed anymore
> Add rel attribute in links and remove unnecessary aria attribute

- infra/modules/aws_lambda_api/outputs.tf
- infra/modules/aws_reverse_proxy/outputs.tf
- infra/modules/main/cloudwatch.tf
This PR adds some useful Lambda, API Gateway & CloudFront metrics to our overview dashboard.
> Dashboard updates

- frontend/public/index.html
- frontend/public/styles.css
- frontend/src/index.tsx
> Add link to hs article about oiretutka to landing page

- infra/logging.tf
- infra/main.tf
...so we can get back to making silly experiments there. :smile:
> Re enable dev-env password

- frontend/embed/v1/public/index.html
- frontend/embed/v1/src/index.css
- frontend/embed/v1/src/index.tsx
Closes #65 
Something fishy happened with the html file – please check that page elements are in correct order.
> Add custom input validations and validation error messages

- backend/src/index.ts
https://www.thesslstore.com/blog/what-is-hypertext-strict-transport-security-hsts/
Closes #73
> Add Strict-Transport-Security headers to API responses.

- frontend/embed/v1/.gitignore
- frontend/embed/v1/package-lock.json
- frontend/embed/v1/package.json
- frontend/embed/v1/public/index.template.html
- frontend/embed/v1/src/translations.json
- frontend/embed/v1/translate.js
- frontend/embed/v1/translate.ts
Not sure exactly _how_ you want to handle this building, but this should be a start. Let me know how to proceed. I'm not fluent in Finnish so I'd need some help with the translations too - but let's get the code in place and then the translations can be taken care of by whomever.
> First attempt at a build script for translations

- frontend/embed/v1/src/index.tsx
Proper fix should come with the updated form validation.
> Add stopgap fix for #133

- backend/src/index.ts
- common/model.ts
- frontend/embed/v1/public/index.html
- infra/modules/main/storage.tf
Issue https://github.com/futurice/symptomradar/issues/151
> Add questions about being in contact with healthcare

- .github/workflows/ci.yml
- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- backend/src/core/main.test.ts
- backend/src/core/main.ts
- common/test/set-up-jest.js
- frontend/embed/v1/.gitignore
- package-lock.json
- package.json
- tsconfig.json
...and a few first tests. :tada: 
This was long overdue.
> Add test runner

- src/frontend/main/About.tsx
- src/frontend/main/FilterToggle.tsx
These were causing errors in the build version.
> Remove inline styles

- src/frontend/main/AppPlaceholder.tsx
- src/index-frontend-main.tsx
> Move standalone site behind feature flag

- src/frontend/main/Privacy.tsx
Fixes issue https://github.com/futurice/symptomradar/issues/166
> Add open data rules to privacy info

- src/frontend/embed/v1/translations.json
English language name was fi, this commit fixes it
> Fix bug in translations.json

- public/tietosuojalauseke.html
- src/frontend/main/Privacy.tsx
Made some clarifications to tietosuoja documentation
> Some clarifications to tietosuoja doc

- infra/modules/main/frontend.tf
> Relax CSP for standalone site

- public/index-embed-v1.html
- src/frontend/embed/v1/translations.json
- src/index-frontend-embed-v1.ts
Showing different text at the beginning of the form for a returning user (id and timestamp in local strorage already).
> Show message for returning user

- .envrc.sample
- README.md
This is the best I could come up within a short time 😁 does it make sense or is it all utter garbage? I tried to take into account all the hurdles I've encountered along the way.
> Update README with local environment setup instructions

- src/frontend/main/Modal.tsx
- src/frontend/main/ModalContent.tsx
- src/frontend/main/map/DorlingCartogram.tsx
Fixing issues with map legends and using proper text
Changing modal to add a column of percentage and typo fixes
> Map legend and modal fixes

- public/index-embed-v1.html
- src/frontend/embed/v1/index.css
- src/index-frontend-embed-v1.ts
> Add language selector for the embed

- src/frontend/main/Survey.tsx
- src/react-app-env.d.ts
…by excluding the child page -part of iframe-resizer lib from the main site bundle.
> Fix framing behaviour

- src/frontend/main/Header.tsx
- src/frontend/main/MapView.tsx
- src/frontend/main/Modal.tsx
Small style adjustments and accessibility fixes
> Style and accessibility adjustments

- src/frontend/main/map/DorlingCartogram.tsx
Change Ylin 10 to Top 10 in the legend
> change Ylin to Top

- src/frontend/embed/v1/translations.json
Small translations updates for English texts related to returning users :)
> Update English translation for returning user texts

- .envrc.sample
- .github/workflows/deploy-dev.yml
- infra/modules/aws_reverse_proxy/lambda.tpl.js
- infra/modules/aws_reverse_proxy/variables.tf
- infra/modules/main/frontend.tf
- infra/modules/main/open_data.tf
- src/frontend/main/App.tsx
- src/frontend/main/MapView.tsx
- src/index-backend.ts
This PR is a follow-up to #233, and fixes All The Things related to CSP, CORS & Auth with regard to accessing the open data site from the UI.
"Way more work than I expected" would be the understatement of the year...
> Fix data fetching

- infra/backend.tf
- infra/main.tf
- infra/modules/aws_lambda_api/certificate.tf
- infra/modules/aws_lambda_api/outputs.tf
- infra/modules/aws_reverse_proxy/certificate.tf
- infra/modules/aws_reverse_proxy/outputs.tf
- infra/modules/main/backend.tf
- infra/modules/main/cloudwatch.tf
- infra/modules/main/outputs.tf
- infra/modules/main/storage.tf
- infra/outputs.tf
Bunch of tiny things I've been dragging my feet pushing up.
> Misc infra changes

- src/frontend/embed/v1/index.css
Hide default browser radio inputs, and show custom styled ::before and ::after elements
> Add custom styling to radio buttons, closes #93

- src/backend/main.ts
- src/backend/queries.ts
- src/index-backend.ts
- Query accumulated response data by postal code with Athena
- Accumulate postal code level data into city level data
- Push data into `city_level_general_results.json`
> City level data dump handler

- infra/modules/main/cloudwatch.tf
> Add basic worker info to dashboard

- infra/modules/main/backend.tf
So now we'd run 4 times per day, top of the hour at 0, 6, 12 and 18 o'clock.
We can always trigger a manual run when we want to see results faster than this (@cutepig already made one).
Closes #265
> Update data dump update scheduling

- src/backend/main.ts
- src/backend/queries.ts
- src/common/io.ts
- src/common/model.ts
Allows doing things like https://jsfiddle.net/87rsew32/:
Closes #264
> Add daily totals data dump

- infra/modules/main/cloudwatch.tf
> Add CloudWatch annotation

- infra/main.tf
- infra/modules/aws_domain_redirect/main.tf
- infra/modules/aws_domain_redirect/providers.tf
- infra/modules/aws_domain_redirect/variables.tf
- infra/modules/aws_domain_redirect/versions.tf
- infra/modules/main/redirects.tf
- infra/modules/main/variables.tf
That is, if you go to oiretutka.fi it redirects you to www.oiretutka.fi.
> Add apex domain redirect

- src/frontend/main/MapView.tsx
- src/frontend/main/TableView.tsx
- src/frontend/main/constants.ts
Calculating a height for the city level data view, so it can be scrolled in the iframe embed.
> Calculate city level data view height in the embed version

- src/frontend/main/MapView.tsx
- src/frontend/main/TableView.tsx
This should fix these issues that happen in article embeds on very small screens
--
> Adjust embed styles to fix problems on small screens

- public/index-embed-v1.html
- src/frontend/embed/v1/index.css
- src/index-frontend-embed-v1.ts
Add fix for issue https://github.com/futurice/symptomradar/issues/147
> Hide main content until the app's css is loaded

- src/frontend/main/map/MapView.tsx
- src/frontend/main/translations.ts
> Improve translations

- src/frontend/main/Modal.tsx
Using flex centering to center the Modal content with respect to the device screen.
> Center modal overlay

- public/index-embed-v1.html
- src/frontend/embed/v1/translations.json
Add `aria-label` attribute for language selector on the survey form
> Add aria-label for language selector
