frontend/embed/v1/public/index.html
frontend/embed/v1/src/index.tsx

added input validation hints visible also via submit handler
added one missing `required` from an input
(if some option is missing it, and user selects the one, browser validation doesn't understand that it's valid) (at least in Chrome)
removed old input change handler

Validation hints on submit

---

infra/README.md
infra/main.tf
infra/modules/main/backend.tf
infra/modules/main/variables.tf
src/backend/main.test.ts
src/backend/main.ts
src/backend/secrets.ts
src/index-backend.ts
src/setupTests.js

This PR splits the global pepper used for `participant_id` hashing into two parts:
* The known pepper, which is the one we've been using thus far. It hasn't really been secret, so for clarity, it's now included directly in the relevant part of Terraform config.
* The secret pepper, which is stored separately from the codebase, Terraform config, and Lambda environments, in AWS Systems Manager Parameter Store.
Using these two together (see a71a182 for the most important change) we'll ensure that even if someone was able to produce a rainbow table of all existing UUID's (not feasible), including our pre-existing pepper (even less feasible), they still would not be able to reverse that into the original UUID (which itself doesn't really identify participants to any meaningful degree). But you …

Add secret pepper for participant_id hashing

---

src/frontend/embed/v1/index.css

This makes it look nicer in HS apps with dark mode
Fixes this:

Add white background color for the embed

---

infra/athena_iam.tf

Reference for iam fine tune policies
* https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage-pass-accesskeys-ssh.html
* https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage-mfa-only.html

add iam policy for athena developers

---

README.md
infra/main.tf

This allows us to keep iterating on the dev side of things, without accidentally `terraform apply`ing to prod.

Pin prod infra to release tag

---

infra/modules/aws_reverse_proxy/cloudfront.tf
infra/modules/aws_reverse_proxy/lambda.tf
infra/modules/aws_reverse_proxy/lambda.tpl.js
infra/modules/aws_reverse_proxy/variables.tf
infra/modules/main/frontend.tf
infra/providers.tf
package.json
public/index-embed-v1.html
scripts/deploy-frontend

tl;dr:
* When requesting a resource that's handled by client-side routing, it won't exist on S3, which will respond with 404, and serve `/index.html` as the error document. Our Lambda@Edge function will now map it to a 200.
* In the same go, masked some headers from upstream we may not want to disclose. Not really for security, but for looking professional. :smirk: 
* Added a `null_resource.cloudfront_lambda_at_edge` that makes Terraform diffs related to the Lambda@Edge changes easier to grok.
* Updated the build process to refer to assets by absolute path, so that if the client-side routing pretends the path is `/foo/bar/baz/`, `index.css` is still fetched from `/index.css`, not `/foo/bar/baz/index.css`.
Closes #171

Fix standalone site routing

---

src/frontend/main/App.tsx
src/frontend/main/Header.tsx
src/frontend/main/MapView.tsx

The path `/map-embed` will render the map without the header component. When embedded, the iframe height should be defined (no resizer needed) and the map will adjust to that. For example:
`<Iframe src="/map-embed" height="600" />`

Add embed version of map

---

src/index-frontend-embed-v1.ts

The validation errors didn't disappear in the "plain" form embed, because there the form is already visible, so the start button is not pressed (`startSurvey()` never called), which also initialised validation. It's now a separate function, that is called also for the plain form.

Make validation init a separate function

---

src/frontend/main/MapView.tsx

For consistency, since we switched to using "kunta" elsewhere.

Change kaupunki to kunta

---

infra/modules/main/abuse_detection.tf
infra/modules/main/backend.tf
infra/modules/main/storage.tf
package.json
src/backend/abuseDetection.test.ts
src/backend/abuseDetection.ts
src/backend/main.test.ts
src/backend/main.ts
src/common/model.ts
src/common/time.ts
src/common/types.ts
src/index-backend.ts

This has been waiting on the backlog for a long time.
tl;dr:
* When a request comes in, we grab its source IP, its `User-Agent` and `X-Forwarded-For`, and call that its "fingerprint"
* Immediately after, we put those values through a one-way hash function, with a secret pepper included, so it can't be reversed
* For each such hashed fingerprint key/value pair, we upsert an item in DynamoDB, e.g. `"2020-03-31T10Z/source_ip/6NehvvOtv6bGjk7FTtutfcozHqX478AVLV1EbcpmV+g=" => 3`
* This means this IP has been seen 3 times within the hour-long time bucket at `2020-03-31T10:xx:yy`
* Each key has a TTL value set up in DynamoDB, so they expire 24 hours after last being written (so the DB doesn't balloon forever)
* We then calculate an "abuse score" for the incoming request, by simply tallying these …

Abuse detection system

---

package-lock.json
package.json
src/backend/abuseDetection.test.ts
src/backend/abuseDetection.ts
src/backend/main.test.ts
src/backend/main.ts
src/backend/secrets.ts
src/index-backend.ts

Alternative to https://github.com/futurice/symptomradar/pull/260
~~Touched `index-backend.ts` and `backend/main.ts`. Left tests and `abuseDetection.ts` in peace.~~
All promise chains in backend code should now be converted to `async` functions (apart from few instances where promise chains are more straightforward, such as https://github.com/futurice/symptomradar/blob/master/src/backend/abuseDetection.test.ts#L308)

Convert promise chains to async functions

---

src/frontend/main/App.tsx
src/frontend/main/Header.tsx
src/frontend/main/MapView.tsx
src/frontend/main/ModalContent.tsx
src/frontend/main/ResponseDataHandler.tsx
src/frontend/main/TableView.tsx
src/frontend/main/constants.ts
src/frontend/main/handleResponseData.tsx

- Adding a new city level data view, that lists all cities and their response data in tables
- Adding a navigation for switching between the map and city level view
- Moving the city select in the table view, filtering the list based on the selected city
- Adding a `ResponseDataHandler` that returns response and symptom counts and percentage values since they are now needed in two different places (`ModalContent` and the `TableView`). Not sure if this is the best way to do it, any suggestions are welcome and this can be refactored later if needed.
The table view on smaller screens
-------------
Selecting a city
-------------
Larger screens

City level data view

---

src/frontend/main/MapView.tsx

The map is embedded to articles without the header, so the map nav buttons didn't have a top border (which normally is the header's bottom border). 
Now it should be like this on the normal site
Small screen
Bigger screen
And like this in the embed version `/map-embed`
Small screen 
Bigger screen

Add borders to map nav buttons in embed view

---

src/frontend/embed/v1/index.css
src/index-frontend-embed-v1.ts

Made the header padding smaller, the embed does not need it since the articles usually have a padding. Screenshots from the article embeds:
Before (on very small screen)
---
After
The code related to languages was causing errors while developing locally, so I also added a fix for that.

Edit form header paddings and add a fix for local development

---

infra/modules/main/backend.tf

Fixes API Lambda permissions to match #269 (to account for `obfuscateLowPopulationPostalCode()`)

Fix Lambda permissions for backend API.

---

src/backend/app.ts
src/backend/main.ts
src/index-backend.ts

Now, this isn't exactly pretty (maybe @cutepig has ideas on prettifying it?), but this PR turns the previously somewhat cryptic API error:
```
ERROR (API) AccessDenied: Access Denied
at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:816:35)
at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> …
```

Improve error descriptions around S3 operations and storage

---

src/frontend/main/ModalContent.tsx
src/frontend/main/TableView.tsx

If a city has less than 25 responses, the content now looks like this

Fix handling low response data

---

src/frontend/main/CityTables.tsx
src/frontend/main/TableView.tsx

Implementing infinity scroll for the TableView (listing all city data). More data is loaded when the end of the page (on oiretutka.fi) or the container (in the embed version) is reached. The tables were moved to a separate component CityTables, where all loading and list filtering happens.
The update was done because loading the whole city list inside an article embed was a bit too much on slow connections and devices with low memory (or at least on my Android phone it made the whole app crash).

Load more content on scroll

---

src/frontend/main/MapView.tsx

If the city has less than 25 responses, it is marked -1 in the data. This changes the total response calculation to skip those values.

Skip counting responses for -1 values

---

src/frontend/main/CityTables.tsx

On some browser + OS combinations (at least Firefox & Linux) the calculation was not reliable. This adds some threshold so it's not required to scroll all the way to the bottom, more content will be loaded a bit before reaching it.
Also some mobile browsers handle these in different ways, some improvements added to make it work better on all devices.

Load more data a bit before reaching the bottom

---

src/frontend/main/App.tsx
src/frontend/main/CityTables.tsx
src/frontend/main/Header.tsx
src/frontend/main/MapView.tsx
src/frontend/main/TableView.tsx
src/frontend/main/constants.ts

The PR moved HEADERHEIGHT, NAVHEIGHT and CITYSELECTHEIGHT to a part inside styled-component's theme.
`theme` was moved to `constants.ts` file to avoid circular import when  `App.tsx` imports `MapView` and `MapView` imports `theme` from `App.tsx`

Move height constants into theme

---

public/index-embed-v1.html
src/frontend/embed/v1/index.css
src/index-frontend-embed-v1.ts

My PR adds a fix for production flickering issues. Because development server uses inline css (probably to accommodate hot reloading) while css files in production and rendered together with index.html file, the reliable way to test is to create a build version and test the that build bundle instead of relying on local dev:
```
npm run frontend-embed-v1-build && npx serve build -p 3000
```

Remove inline script and use a div for showing loader

---

README.md
package-lock.json
package.json
src/backend/app.ts
src/backend/appMocks.ts
src/backend/cli.ts
src/backend/dataExports/cityLevelGeneralResults.ts
src/backend/dataExports/dailyTotals.ts
src/backend/dataExports/openDataIndex.ts
src/backend/dataExports/totalResponses.ts
src/common/model.ts

Add a local CLI tool to create local open data dumps. Can be developed in the future to update the data dumps to S3 as well.
Example use:
```sh
npm run ts-node src/backend/cli.ts dump daily_totals.json
```
Note that if used via `npm run ts-node` all `--` options have to be followed after a `--`, for e.g.
```sh
npm run ts-node src/backend/cli.ts -- --help
npm run ts-node src/backend/cli.ts dump -- --help
npm run ts-node src/backend/cli.ts dump daily_totals.json -- --out=/tmp/daily_totals.json
```

Open data dump CLI tool

---

infra/modules/main/backend.tf

Looking at our costs, they're dominated by storage:
...which means S3:
...which should mostly be Athena scanning the data.
I don't think anyone minds a bit of delay in the results at this point.

Change backend worker process to run once per day

---

README.md
infra/main.tf
src/frontend/main/MainWrapper.tsx
src/frontend/main/Overview/index.tsx
src/react-app-env.d.ts

- Add iframe resize support for Overview embed
- Fix comment about the map view router structure `/overview -> Overview` instead of `/overview -> MapView`
- Add Overview embed section in README
To test, we could modify the `Survey.tsx` file (which already has iframeResizer "parent" part loaded).
Change the Survey component's code to:
```
const Survey = (props: RouteComponentProps) => {
const [iframeSrc, setIframeSrc] = useState('/embed/v1/?variant=plain');
const currentLanguage = i18n.language;
useEffect(() => {
iframeResizer({ log: false }, '.formIframe');
const newUrl =
currentLanguage === 'fi' ? 'http://localhost:3000/map-embed/overview' : 'http://localhost:3000/map-embed';
setIframeSrc(newUrl);
}, [currentLanguage]);
return (
<Container>
<Iframe className="formIframe" title="Map …
```

Auto resize overview embed

---

src/backend/app.ts
src/backend/appMocks.ts
src/backend/cli.ts
src/backend/dataExports/cityLevelDailyTotals.ts
src/backend/dataExports/cityLevelGeneralResults.ts
src/backend/dataExports/openDataIndex.ts
src/backend/dataExports/postalCodeLevelGeneralResults.ts
src/backend/dataExports/queryUtils.test.ts
src/backend/dataExports/queryUtils.ts
src/backend/dataExports/totalResponses.ts

Closes #299 
City level daily totals data dump
- Adds new `city_level_daily_totals.json` open data file
- Adds `healthcare_contact` field to city and postal code sets
- Fixes `null`-field issues with accumulated data
- Postal codes/cities are filtered as in city-level general results:
- Postal codes are mapped using `low_population_postal_codes.json`
- Postal codes and cities not found in `population_per_city.json` are ignored

City level daily totals data dump

---

src/frontend/main/FilterToggle.tsx
src/frontend/main/Modal.tsx
src/frontend/main/Overview/Body.tsx
src/frontend/main/Overview/index.tsx

We try to center the dialog into the device's screen, but in case of iframe, the whole iframe's length is taken into account instead of the device's screen size, so the modal is cut off from the screen, resulting in something like this.
Firefox seems to respect the focus set to close button when the modal opens, and manages to scroll back to fit the modal to the top of the page, but this is not the case for Chrome : (
So I decided to place the Timeline modal al the bottom of the page if it is embedded.

Position timeline filter at the bottom of the iframe in embed mode
